Vagrant.configure("2") do |config|

    config.vm.define "vm1" do |vm1|
        vm1.vm.box = "centos/7"
        vm1.vm.provider "virtualbox" do |vbox1|
            vbox1.memory = 512  
        end   
        vm1.vm.network "private_network", type: "dhcp"
    end
    
    config.vm.provision "shell" do |s1|
        ssh_pub_key = 
File.readlines("/home/lenka/.ssh/id_rsa.pub").first.strip
    s1.inline = <<-SHELL
        mkdir /root/.ssh
	echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys
        echo #{ssh_pub_key} >> /root/.ssh/authorized_keys
    SHELL
    end

    config.vm.define "vm2" do |vm2|
        vm2.vm.box = "centos/7"
        vm2.vm.provider "virtualbox" do |vbox2|
            vbox2.memory = 512
        end
        vm2.vm.network "private_network", type: "dhcp"
    end

    config.vm.provision "shell" do |s2|
        ssh_pub_key =
File.readlines("/home/lenka/.ssh/id_rsa.pub").first.strip
    s2.inline = <<-SHELL
        echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys
        echo #{ssh_pub_key} >> /root/.ssh/authorized_keys
    SHELL
    end


    config.vm.define "vm3" do |vm3|
        vm3.vm.box = "centos/7"
        vm3.vm.provider "virtualbox" do |vbox3|
            vbox3.memory = 512
        end
        vm3.vm.network "private_network", type: "dhcp"
    end

    config.vm.provision "shell" do |s3|
        ssh_pub_key =
File.readlines("/home/lenka/.ssh/id_rsa.pub").first.strip
    s3.inline = <<-SHELL
        echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys
        echo #{ssh_pub_key} >> /root/.ssh/authorized_keys
    SHELL
    end


    config.vm.define "vm4" do |vm4|
        vm4.vm.box = "centos/7"
        vm4.vm.provider "virtualbox" do |vbox4|
            vbox4.memory = 512
        end
        vm4.vm.network "private_network", type: "dhcp"
    end

config.vm.provision "shell" do |s4|
        ssh_pub_key =
File.readlines("/home/lenka/.ssh/id_rsa.pub").first.strip
    s4.inline = <<-SHELL
        echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys
        echo #{ssh_pub_key} >> /root/.ssh/authorized_keys
    SHELL
    end
end
